//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguradora
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Aditamento
    {
        public int Codigo { get; set; }
        public string Nome { get; set; }
        public string Descriao { get; set; }
        public Nullable<int> Categoria { get; set; }
        public Nullable<int> Marca { get; set; }
        public Nullable<int> Modelo { get; set; }

        [DataType(DataType.Date)]
        public Nullable<System.DateTime> AnoFabricacao { get; set; }
    
        public virtual Marca Marca1 { get; set; }
        public virtual Modelo Modelo1 { get; set; }
    }
}
