//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguradora
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnoModelo
    {
        public AnoModelo()
        {
            this.Veiculo = new HashSet<Veiculo>();
            this.Cotacao = new HashSet<Cotacao>();
            this.ObjetoSegurado = new HashSet<ObjetoSegurado>();
        }
    
        public int ID { get; set; }
        public string Codigo { get; set; }
        public string Descricao { get; set; }
        public int Marca { get; set; }
        public int Modelo { get; set; }
        public int TipoVeiculo { get; set; }
    
        public virtual Marca Marca1 { get; set; }
        public virtual Modelo Modelo1 { get; set; }
        public virtual ICollection<Veiculo> Veiculo { get; set; }
        public virtual ICollection<Cotacao> Cotacao { get; set; }
        public virtual ICollection<ObjetoSegurado> ObjetoSegurado { get; set; }
    }
}
