//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguradora
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apolice
    {
        public Apolice()
        {
            this.Sinistro = new HashSet<Sinistro>();
        }
    
        public int ID { get; set; }
        public int Cotacao { get; set; }
        public Nullable<int> NroAditivo { get; set; }
        public Nullable<int> Segurado { get; set; }
        public Nullable<int> ObjetoSegurado { get; set; }
        public Nullable<System.DateTime> DataVigencia { get; set; }
        public Nullable<System.DateTime> DataPrimeiraParcela { get; set; }
    
        public virtual ObjetoSegurado ObjetoSegurado1 { get; set; }
        public virtual Segurado Segurado1 { get; set; }
        public virtual ICollection<Sinistro> Sinistro { get; set; }
        public virtual Cotacao Cotacao1 { get; set; }
    }
}
