//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguradora
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cotacao
    {
        public Cotacao()
        {
            this.Apolice = new HashSet<Apolice>();
        }
    
        public int Codigo { get; set; }
        public Nullable<int> NumeroAditivo { get; set; }
        public Nullable<int> Modalidade { get; set; }
        public Nullable<System.DateTime> DataInicial { get; set; }
        public Nullable<System.DateTime> DataFinal { get; set; }
        public Nullable<int> Segurado { get; set; }
        public Nullable<int> Marca { get; set; }
        public Nullable<int> Modelo { get; set; }
        public Nullable<int> Veiculo { get; set; }
        public Nullable<int> AnoModelo { get; set; }
        public bool SeguradoCondutor { get; set; }
        public Nullable<decimal> PercentualCoeficiente { get; set; }
        public Nullable<decimal> PercentualDesconto { get; set; }
        public Nullable<int> TipoUso { get; set; }
        public Nullable<int> PernoiteDoVeiculo { get; set; }
        public string Observacoes { get; set; }
        public string InformacoesGerais { get; set; }
        public Nullable<decimal> ValorTotal { get; set; }
    
        public virtual ICollection<Apolice> Apolice { get; set; }
        public virtual Segurado Segurado1 { get; set; }
        public virtual Marca Marca1 { get; set; }
        public virtual Modelo Modelo1 { get; set; }
        public virtual Veiculo Veiculo1 { get; set; }
        public virtual AnoModelo AnoModelo1 { get; set; }
    }
}
