//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguradora
{
    using System;
    using System.Collections.Generic;
    
    public partial class CotacaoAditamento
    {
        public int Codigo { get; set; }
        public int Cotacao { get; set; }
        public int Aditamento { get; set; }
    
        public virtual Aditamento Aditamento1 { get; set; }
    }
}
