//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguradora
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marca
    {
        public Marca()
        {
            this.AnoModelo = new HashSet<AnoModelo>();
            this.Modelo = new HashSet<Modelo>();
            this.ObjetoSegurado = new HashSet<ObjetoSegurado>();
            this.Veiculo = new HashSet<Veiculo>();
        }
    
        public int ID { get; set; }
        public string Codigo { get; set; }
        public string Descricao { get; set; }
        public int TipoVeiculo { get; set; }
    
        public virtual ICollection<AnoModelo> AnoModelo { get; set; }
        public virtual ICollection<Modelo> Modelo { get; set; }
        public virtual ICollection<ObjetoSegurado> ObjetoSegurado { get; set; }
        public virtual ICollection<Veiculo> Veiculo { get; set; }
    }
}
