//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguradora
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Segurado
    {
        public Segurado()
        {
            this.ObjetoSegurado = new HashSet<ObjetoSegurado>();
            this.Apolice = new HashSet<Apolice>();
        }
    
        public int Codigo { get; set; }
        public string Nome { get; set; }
        public string Documento { get; set; }
        public System.DateTime DataNascimento { get; set; }
        public int Sexo { get; set; }
        public int EstadoCivil { get; set; }

        [DataType(DataType.PhoneNumber)]
        public string FoneResidencial { get; set; }

        [DataType(DataType.PhoneNumber)]
        public string FoneCelular { get; set; }

        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        public string Rua { get; set; }
        public string Numero { get; set; }
        public string Bairro { get; set; }

        public string CEP { get; set; }
        public string Cidade { get; set; }
        public string Estado { get; set; }
        public string BonusAtual { get; set; }
        public string SeguradoraAnterior { get; set; }
        public string NumeroCNH { get; set; }

        [DataType(DataType.Date)]
        public System.DateTime PrimeiraHabilitacao { get; set; }
    
        public virtual ICollection<ObjetoSegurado> ObjetoSegurado { get; set; }
        public virtual ObjetoSegurado ObjetoSegurado1 { get; set; }
        public virtual ICollection<Apolice> Apolice { get; set; }
    }
}
