//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguradora
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sinistro
    {
        public int Codigo { get; set; }
        public int NroContrato { get; set; }
        public string NroBO { get; set; }
        public string Avarias { get; set; }
        public string DescricaoOcorrido { get; set; }
    
        public virtual Apolice Apolice { get; set; }
    }
}
