#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguradora.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="seguradora")]
	public partial class ModeloDadosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAnoModelo(AnoModelo instance);
    partial void UpdateAnoModelo(AnoModelo instance);
    partial void DeleteAnoModelo(AnoModelo instance);
    partial void InsertMarca(Marca instance);
    partial void UpdateMarca(Marca instance);
    partial void DeleteMarca(Marca instance);
    partial void InsertModelo(Modelo instance);
    partial void UpdateModelo(Modelo instance);
    partial void DeleteModelo(Modelo instance);
    partial void InsertVeiculo(Veiculo instance);
    partial void UpdateVeiculo(Veiculo instance);
    partial void DeleteVeiculo(Veiculo instance);
    partial void InsertSegurado(Segurado instance);
    partial void UpdateSegurado(Segurado instance);
    partial void DeleteSegurado(Segurado instance);
    partial void InsertObjetoSegurado(ObjetoSegurado instance);
    partial void UpdateObjetoSegurado(ObjetoSegurado instance);
    partial void DeleteObjetoSegurado(ObjetoSegurado instance);
    #endregion
		
		public ModeloDadosDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["seguroConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ModeloDadosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModeloDadosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModeloDadosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModeloDadosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AnoModelo> AnoModelos
		{
			get
			{
				return this.GetTable<AnoModelo>();
			}
		}
		
		public System.Data.Linq.Table<Marca> Marcas
		{
			get
			{
				return this.GetTable<Marca>();
			}
		}
		
		public System.Data.Linq.Table<Modelo> Modelos
		{
			get
			{
				return this.GetTable<Modelo>();
			}
		}
		
		public System.Data.Linq.Table<Veiculo> Veiculos
		{
			get
			{
				return this.GetTable<Veiculo>();
			}
		}
		
		public System.Data.Linq.Table<Segurado> Segurados
		{
			get
			{
				return this.GetTable<Segurado>();
			}
		}
		
		public System.Data.Linq.Table<ObjetoSegurado> ObjetoSegurados
		{
			get
			{
				return this.GetTable<ObjetoSegurado>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AnoModelo")]
	public partial class AnoModelo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Codigo;
		
		private string _Descricao;
		
		private int _Marca;
		
		private int _Modelo;
		
		private int _TipoVeiculo;
		
		private EntitySet<Veiculo> _Veiculos;
		
		private EntityRef<Marca> _Marca1;
		
		private EntityRef<Modelo> _Modelo1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCodigoChanging(string value);
    partial void OnCodigoChanged();
    partial void OnDescricaoChanging(string value);
    partial void OnDescricaoChanged();
    partial void OnMarcaChanging(int value);
    partial void OnMarcaChanged();
    partial void OnModeloChanging(int value);
    partial void OnModeloChanged();
    partial void OnTipoVeiculoChanging(int value);
    partial void OnTipoVeiculoChanged();
    #endregion
		
		public AnoModelo()
		{
			this._Veiculos = new EntitySet<Veiculo>(new Action<Veiculo>(this.attach_Veiculos), new Action<Veiculo>(this.detach_Veiculos));
			this._Marca1 = default(EntityRef<Marca>);
			this._Modelo1 = default(EntityRef<Modelo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descricao", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Descricao
		{
			get
			{
				return this._Descricao;
			}
			set
			{
				if ((this._Descricao != value))
				{
					this.OnDescricaoChanging(value);
					this.SendPropertyChanging();
					this._Descricao = value;
					this.SendPropertyChanged("Descricao");
					this.OnDescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marca", DbType="Int NOT NULL")]
		public int Marca
		{
			get
			{
				return this._Marca;
			}
			set
			{
				if ((this._Marca != value))
				{
					if (this._Marca1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMarcaChanging(value);
					this.SendPropertyChanging();
					this._Marca = value;
					this.SendPropertyChanged("Marca");
					this.OnMarcaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modelo", DbType="Int NOT NULL")]
		public int Modelo
		{
			get
			{
				return this._Modelo;
			}
			set
			{
				if ((this._Modelo != value))
				{
					if (this._Modelo1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnModeloChanging(value);
					this.SendPropertyChanging();
					this._Modelo = value;
					this.SendPropertyChanged("Modelo");
					this.OnModeloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoVeiculo", DbType="Int NOT NULL")]
		public int TipoVeiculo
		{
			get
			{
				return this._TipoVeiculo;
			}
			set
			{
				if ((this._TipoVeiculo != value))
				{
					this.OnTipoVeiculoChanging(value);
					this.SendPropertyChanging();
					this._TipoVeiculo = value;
					this.SendPropertyChanged("TipoVeiculo");
					this.OnTipoVeiculoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AnoModelo_Veiculo", Storage="_Veiculos", ThisKey="ID", OtherKey="AnoModelo")]
		public EntitySet<Veiculo> Veiculos
		{
			get
			{
				return this._Veiculos;
			}
			set
			{
				this._Veiculos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Marca_AnoModelo", Storage="_Marca1", ThisKey="Marca", OtherKey="ID", IsForeignKey=true)]
		public Marca Marca1
		{
			get
			{
				return this._Marca1.Entity;
			}
			set
			{
				Marca previousValue = this._Marca1.Entity;
				if (((previousValue != value) 
							|| (this._Marca1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Marca1.Entity = null;
						previousValue.AnoModelos.Remove(this);
					}
					this._Marca1.Entity = value;
					if ((value != null))
					{
						value.AnoModelos.Add(this);
						this._Marca = value.ID;
					}
					else
					{
						this._Marca = default(int);
					}
					this.SendPropertyChanged("Marca1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Modelo_AnoModelo", Storage="_Modelo1", ThisKey="Modelo", OtherKey="ID", IsForeignKey=true)]
		public Modelo Modelo1
		{
			get
			{
				return this._Modelo1.Entity;
			}
			set
			{
				Modelo previousValue = this._Modelo1.Entity;
				if (((previousValue != value) 
							|| (this._Modelo1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Modelo1.Entity = null;
						previousValue.AnoModelos.Remove(this);
					}
					this._Modelo1.Entity = value;
					if ((value != null))
					{
						value.AnoModelos.Add(this);
						this._Modelo = value.ID;
					}
					else
					{
						this._Modelo = default(int);
					}
					this.SendPropertyChanged("Modelo1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Veiculos(Veiculo entity)
		{
			this.SendPropertyChanging();
			entity.AnoModelo1 = this;
		}
		
		private void detach_Veiculos(Veiculo entity)
		{
			this.SendPropertyChanging();
			entity.AnoModelo1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Marca")]
	public partial class Marca : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Codigo;
		
		private string _Descricao;
		
		private int _TipoVeiculo;
		
		private EntitySet<AnoModelo> _AnoModelos;
		
		private EntitySet<Modelo> _Modelos;
		
		private EntitySet<Veiculo> _Veiculos;
		
		private EntitySet<ObjetoSegurado> _ObjetoSegurados;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCodigoChanging(string value);
    partial void OnCodigoChanged();
    partial void OnDescricaoChanging(string value);
    partial void OnDescricaoChanged();
    partial void OnTipoVeiculoChanging(int value);
    partial void OnTipoVeiculoChanged();
    #endregion
		
		public Marca()
		{
			this._AnoModelos = new EntitySet<AnoModelo>(new Action<AnoModelo>(this.attach_AnoModelos), new Action<AnoModelo>(this.detach_AnoModelos));
			this._Modelos = new EntitySet<Modelo>(new Action<Modelo>(this.attach_Modelos), new Action<Modelo>(this.detach_Modelos));
			this._Veiculos = new EntitySet<Veiculo>(new Action<Veiculo>(this.attach_Veiculos), new Action<Veiculo>(this.detach_Veiculos));
			this._ObjetoSegurados = new EntitySet<ObjetoSegurado>(new Action<ObjetoSegurado>(this.attach_ObjetoSegurados), new Action<ObjetoSegurado>(this.detach_ObjetoSegurados));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descricao", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Descricao
		{
			get
			{
				return this._Descricao;
			}
			set
			{
				if ((this._Descricao != value))
				{
					this.OnDescricaoChanging(value);
					this.SendPropertyChanging();
					this._Descricao = value;
					this.SendPropertyChanged("Descricao");
					this.OnDescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoVeiculo", DbType="Int NOT NULL")]
		public int TipoVeiculo
		{
			get
			{
				return this._TipoVeiculo;
			}
			set
			{
				if ((this._TipoVeiculo != value))
				{
					this.OnTipoVeiculoChanging(value);
					this.SendPropertyChanging();
					this._TipoVeiculo = value;
					this.SendPropertyChanged("TipoVeiculo");
					this.OnTipoVeiculoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Marca_AnoModelo", Storage="_AnoModelos", ThisKey="ID", OtherKey="Marca")]
		public EntitySet<AnoModelo> AnoModelos
		{
			get
			{
				return this._AnoModelos;
			}
			set
			{
				this._AnoModelos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Marca_Modelo", Storage="_Modelos", ThisKey="ID", OtherKey="Marca")]
		public EntitySet<Modelo> Modelos
		{
			get
			{
				return this._Modelos;
			}
			set
			{
				this._Modelos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Marca_Veiculo", Storage="_Veiculos", ThisKey="ID", OtherKey="Marca")]
		public EntitySet<Veiculo> Veiculos
		{
			get
			{
				return this._Veiculos;
			}
			set
			{
				this._Veiculos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Marca_ObjetoSegurado", Storage="_ObjetoSegurados", ThisKey="ID", OtherKey="Marca")]
		public EntitySet<ObjetoSegurado> ObjetoSegurados
		{
			get
			{
				return this._ObjetoSegurados;
			}
			set
			{
				this._ObjetoSegurados.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_AnoModelos(AnoModelo entity)
		{
			this.SendPropertyChanging();
			entity.Marca1 = this;
		}
		
		private void detach_AnoModelos(AnoModelo entity)
		{
			this.SendPropertyChanging();
			entity.Marca1 = null;
		}
		
		private void attach_Modelos(Modelo entity)
		{
			this.SendPropertyChanging();
			entity.Marca1 = this;
		}
		
		private void detach_Modelos(Modelo entity)
		{
			this.SendPropertyChanging();
			entity.Marca1 = null;
		}
		
		private void attach_Veiculos(Veiculo entity)
		{
			this.SendPropertyChanging();
			entity.Marca1 = this;
		}
		
		private void detach_Veiculos(Veiculo entity)
		{
			this.SendPropertyChanging();
			entity.Marca1 = null;
		}
		
		private void attach_ObjetoSegurados(ObjetoSegurado entity)
		{
			this.SendPropertyChanging();
			entity.Marca1 = this;
		}
		
		private void detach_ObjetoSegurados(ObjetoSegurado entity)
		{
			this.SendPropertyChanging();
			entity.Marca1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Modelo")]
	public partial class Modelo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Codigo;
		
		private string _Descricao;
		
		private int _Marca;
		
		private int _TipoVeiculo;
		
		private EntitySet<AnoModelo> _AnoModelos;
		
		private EntitySet<Veiculo> _Veiculos;
		
		private EntitySet<ObjetoSegurado> _ObjetoSegurados;
		
		private EntityRef<Marca> _Marca1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCodigoChanging(string value);
    partial void OnCodigoChanged();
    partial void OnDescricaoChanging(string value);
    partial void OnDescricaoChanged();
    partial void OnMarcaChanging(int value);
    partial void OnMarcaChanged();
    partial void OnTipoVeiculoChanging(int value);
    partial void OnTipoVeiculoChanged();
    #endregion
		
		public Modelo()
		{
			this._AnoModelos = new EntitySet<AnoModelo>(new Action<AnoModelo>(this.attach_AnoModelos), new Action<AnoModelo>(this.detach_AnoModelos));
			this._Veiculos = new EntitySet<Veiculo>(new Action<Veiculo>(this.attach_Veiculos), new Action<Veiculo>(this.detach_Veiculos));
			this._ObjetoSegurados = new EntitySet<ObjetoSegurado>(new Action<ObjetoSegurado>(this.attach_ObjetoSegurados), new Action<ObjetoSegurado>(this.detach_ObjetoSegurados));
			this._Marca1 = default(EntityRef<Marca>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descricao", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Descricao
		{
			get
			{
				return this._Descricao;
			}
			set
			{
				if ((this._Descricao != value))
				{
					this.OnDescricaoChanging(value);
					this.SendPropertyChanging();
					this._Descricao = value;
					this.SendPropertyChanged("Descricao");
					this.OnDescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marca", DbType="Int NOT NULL")]
		public int Marca
		{
			get
			{
				return this._Marca;
			}
			set
			{
				if ((this._Marca != value))
				{
					if (this._Marca1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMarcaChanging(value);
					this.SendPropertyChanging();
					this._Marca = value;
					this.SendPropertyChanged("Marca");
					this.OnMarcaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoVeiculo", DbType="Int NOT NULL")]
		public int TipoVeiculo
		{
			get
			{
				return this._TipoVeiculo;
			}
			set
			{
				if ((this._TipoVeiculo != value))
				{
					this.OnTipoVeiculoChanging(value);
					this.SendPropertyChanging();
					this._TipoVeiculo = value;
					this.SendPropertyChanged("TipoVeiculo");
					this.OnTipoVeiculoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Modelo_AnoModelo", Storage="_AnoModelos", ThisKey="ID", OtherKey="Modelo")]
		public EntitySet<AnoModelo> AnoModelos
		{
			get
			{
				return this._AnoModelos;
			}
			set
			{
				this._AnoModelos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Modelo_Veiculo", Storage="_Veiculos", ThisKey="ID", OtherKey="Modelo")]
		public EntitySet<Veiculo> Veiculos
		{
			get
			{
				return this._Veiculos;
			}
			set
			{
				this._Veiculos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Modelo_ObjetoSegurado", Storage="_ObjetoSegurados", ThisKey="ID", OtherKey="Modelo")]
		public EntitySet<ObjetoSegurado> ObjetoSegurados
		{
			get
			{
				return this._ObjetoSegurados;
			}
			set
			{
				this._ObjetoSegurados.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Marca_Modelo", Storage="_Marca1", ThisKey="Marca", OtherKey="ID", IsForeignKey=true)]
		public Marca Marca1
		{
			get
			{
				return this._Marca1.Entity;
			}
			set
			{
				Marca previousValue = this._Marca1.Entity;
				if (((previousValue != value) 
							|| (this._Marca1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Marca1.Entity = null;
						previousValue.Modelos.Remove(this);
					}
					this._Marca1.Entity = value;
					if ((value != null))
					{
						value.Modelos.Add(this);
						this._Marca = value.ID;
					}
					else
					{
						this._Marca = default(int);
					}
					this.SendPropertyChanged("Marca1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_AnoModelos(AnoModelo entity)
		{
			this.SendPropertyChanging();
			entity.Modelo1 = this;
		}
		
		private void detach_AnoModelos(AnoModelo entity)
		{
			this.SendPropertyChanging();
			entity.Modelo1 = null;
		}
		
		private void attach_Veiculos(Veiculo entity)
		{
			this.SendPropertyChanging();
			entity.Modelo1 = this;
		}
		
		private void detach_Veiculos(Veiculo entity)
		{
			this.SendPropertyChanging();
			entity.Modelo1 = null;
		}
		
		private void attach_ObjetoSegurados(ObjetoSegurado entity)
		{
			this.SendPropertyChanging();
			entity.Modelo1 = this;
		}
		
		private void detach_ObjetoSegurados(ObjetoSegurado entity)
		{
			this.SendPropertyChanging();
			entity.Modelo1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Veiculo")]
	public partial class Veiculo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private decimal _Valor;
		
		private int _Marca;
		
		private int _Modelo;
		
		private int _AnoModelo;
		
		private string _Combustivel;
		
		private string _CodigoFipe;
		
		private string _MesReferencia;
		
		private int _TipoVeiculo;
		
		private string _SiglaCombustivel;
		
		private EntityRef<AnoModelo> _AnoModelo1;
		
		private EntityRef<Marca> _Marca1;
		
		private EntityRef<Modelo> _Modelo1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnValorChanging(decimal value);
    partial void OnValorChanged();
    partial void OnMarcaChanging(int value);
    partial void OnMarcaChanged();
    partial void OnModeloChanging(int value);
    partial void OnModeloChanged();
    partial void OnAnoModeloChanging(int value);
    partial void OnAnoModeloChanged();
    partial void OnCombustivelChanging(string value);
    partial void OnCombustivelChanged();
    partial void OnCodigoFipeChanging(string value);
    partial void OnCodigoFipeChanged();
    partial void OnMesReferenciaChanging(string value);
    partial void OnMesReferenciaChanged();
    partial void OnTipoVeiculoChanging(int value);
    partial void OnTipoVeiculoChanged();
    partial void OnSiglaCombustivelChanging(string value);
    partial void OnSiglaCombustivelChanged();
    #endregion
		
		public Veiculo()
		{
			this._AnoModelo1 = default(EntityRef<AnoModelo>);
			this._Marca1 = default(EntityRef<Marca>);
			this._Modelo1 = default(EntityRef<Modelo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Valor", DbType="Decimal(10,2) NOT NULL")]
		public decimal Valor
		{
			get
			{
				return this._Valor;
			}
			set
			{
				if ((this._Valor != value))
				{
					this.OnValorChanging(value);
					this.SendPropertyChanging();
					this._Valor = value;
					this.SendPropertyChanged("Valor");
					this.OnValorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marca", DbType="Int NOT NULL")]
		public int Marca
		{
			get
			{
				return this._Marca;
			}
			set
			{
				if ((this._Marca != value))
				{
					if (this._Marca1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMarcaChanging(value);
					this.SendPropertyChanging();
					this._Marca = value;
					this.SendPropertyChanged("Marca");
					this.OnMarcaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modelo", DbType="Int NOT NULL")]
		public int Modelo
		{
			get
			{
				return this._Modelo;
			}
			set
			{
				if ((this._Modelo != value))
				{
					if (this._Modelo1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnModeloChanging(value);
					this.SendPropertyChanging();
					this._Modelo = value;
					this.SendPropertyChanged("Modelo");
					this.OnModeloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnoModelo", DbType="Int NOT NULL")]
		public int AnoModelo
		{
			get
			{
				return this._AnoModelo;
			}
			set
			{
				if ((this._AnoModelo != value))
				{
					if (this._AnoModelo1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAnoModeloChanging(value);
					this.SendPropertyChanging();
					this._AnoModelo = value;
					this.SendPropertyChanged("AnoModelo");
					this.OnAnoModeloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Combustivel", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Combustivel
		{
			get
			{
				return this._Combustivel;
			}
			set
			{
				if ((this._Combustivel != value))
				{
					this.OnCombustivelChanging(value);
					this.SendPropertyChanging();
					this._Combustivel = value;
					this.SendPropertyChanged("Combustivel");
					this.OnCombustivelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoFipe", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string CodigoFipe
		{
			get
			{
				return this._CodigoFipe;
			}
			set
			{
				if ((this._CodigoFipe != value))
				{
					this.OnCodigoFipeChanging(value);
					this.SendPropertyChanging();
					this._CodigoFipe = value;
					this.SendPropertyChanged("CodigoFipe");
					this.OnCodigoFipeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MesReferencia", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string MesReferencia
		{
			get
			{
				return this._MesReferencia;
			}
			set
			{
				if ((this._MesReferencia != value))
				{
					this.OnMesReferenciaChanging(value);
					this.SendPropertyChanging();
					this._MesReferencia = value;
					this.SendPropertyChanged("MesReferencia");
					this.OnMesReferenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoVeiculo", DbType="Int NOT NULL")]
		public int TipoVeiculo
		{
			get
			{
				return this._TipoVeiculo;
			}
			set
			{
				if ((this._TipoVeiculo != value))
				{
					this.OnTipoVeiculoChanging(value);
					this.SendPropertyChanging();
					this._TipoVeiculo = value;
					this.SendPropertyChanged("TipoVeiculo");
					this.OnTipoVeiculoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiglaCombustivel", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string SiglaCombustivel
		{
			get
			{
				return this._SiglaCombustivel;
			}
			set
			{
				if ((this._SiglaCombustivel != value))
				{
					this.OnSiglaCombustivelChanging(value);
					this.SendPropertyChanging();
					this._SiglaCombustivel = value;
					this.SendPropertyChanged("SiglaCombustivel");
					this.OnSiglaCombustivelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AnoModelo_Veiculo", Storage="_AnoModelo1", ThisKey="AnoModelo", OtherKey="ID", IsForeignKey=true)]
		public AnoModelo AnoModelo1
		{
			get
			{
				return this._AnoModelo1.Entity;
			}
			set
			{
				AnoModelo previousValue = this._AnoModelo1.Entity;
				if (((previousValue != value) 
							|| (this._AnoModelo1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._AnoModelo1.Entity = null;
						previousValue.Veiculos.Remove(this);
					}
					this._AnoModelo1.Entity = value;
					if ((value != null))
					{
						value.Veiculos.Add(this);
						this._AnoModelo = value.ID;
					}
					else
					{
						this._AnoModelo = default(int);
					}
					this.SendPropertyChanged("AnoModelo1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Marca_Veiculo", Storage="_Marca1", ThisKey="Marca", OtherKey="ID", IsForeignKey=true)]
		public Marca Marca1
		{
			get
			{
				return this._Marca1.Entity;
			}
			set
			{
				Marca previousValue = this._Marca1.Entity;
				if (((previousValue != value) 
							|| (this._Marca1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Marca1.Entity = null;
						previousValue.Veiculos.Remove(this);
					}
					this._Marca1.Entity = value;
					if ((value != null))
					{
						value.Veiculos.Add(this);
						this._Marca = value.ID;
					}
					else
					{
						this._Marca = default(int);
					}
					this.SendPropertyChanged("Marca1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Modelo_Veiculo", Storage="_Modelo1", ThisKey="Modelo", OtherKey="ID", IsForeignKey=true)]
		public Modelo Modelo1
		{
			get
			{
				return this._Modelo1.Entity;
			}
			set
			{
				Modelo previousValue = this._Modelo1.Entity;
				if (((previousValue != value) 
							|| (this._Modelo1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Modelo1.Entity = null;
						previousValue.Veiculos.Remove(this);
					}
					this._Modelo1.Entity = value;
					if ((value != null))
					{
						value.Veiculos.Add(this);
						this._Modelo = value.ID;
					}
					else
					{
						this._Modelo = default(int);
					}
					this.SendPropertyChanged("Modelo1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Segurado")]
	public partial class Segurado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Codigo;
		
		private string _Nome;
		
		private string _Documento;
		
		private System.DateTime _DataNascimento;
		
		private int _Sexo;
		
		private int _EstadoCivil;
		
		private string _FoneResidencial;
		
		private string _FoneCelular;
		
		private string _Email;
		
		private string _Rua;
		
		private string _Numero;
		
		private string _Bairro;
		
		private string _CEP;
		
		private string _Cidade;
		
		private string _Estado;
		
		private string _BonusAtual;
		
		private string _SeguradoraAnterior;
		
		private string _NumeroCNH;
		
		private System.DateTime _PrimeiraHabilitacao;
		
		private EntitySet<ObjetoSegurado> _ObjetoSegurados;
		
		private EntityRef<ObjetoSegurado> _ObjetoSegurado;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoChanging(int value);
    partial void OnCodigoChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnDocumentoChanging(string value);
    partial void OnDocumentoChanged();
    partial void OnDataNascimentoChanging(System.DateTime value);
    partial void OnDataNascimentoChanged();
    partial void OnSexoChanging(int value);
    partial void OnSexoChanged();
    partial void OnEstadoCivilChanging(int value);
    partial void OnEstadoCivilChanged();
    partial void OnFoneResidencialChanging(string value);
    partial void OnFoneResidencialChanged();
    partial void OnFoneCelularChanging(string value);
    partial void OnFoneCelularChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnRuaChanging(string value);
    partial void OnRuaChanged();
    partial void OnNumeroChanging(string value);
    partial void OnNumeroChanged();
    partial void OnBairroChanging(string value);
    partial void OnBairroChanged();
    partial void OnCEPChanging(string value);
    partial void OnCEPChanged();
    partial void OnCidadeChanging(string value);
    partial void OnCidadeChanged();
    partial void OnEstadoChanging(string value);
    partial void OnEstadoChanged();
    partial void OnBonusAtualChanging(string value);
    partial void OnBonusAtualChanged();
    partial void OnSeguradoraAnteriorChanging(string value);
    partial void OnSeguradoraAnteriorChanged();
    partial void OnNumeroCNHChanging(string value);
    partial void OnNumeroCNHChanged();
    partial void OnPrimeiraHabilitacaoChanging(System.DateTime value);
    partial void OnPrimeiraHabilitacaoChanged();
    #endregion
		
		public Segurado()
		{
			this._ObjetoSegurados = new EntitySet<ObjetoSegurado>(new Action<ObjetoSegurado>(this.attach_ObjetoSegurados), new Action<ObjetoSegurado>(this.detach_ObjetoSegurados));
			this._ObjetoSegurado = default(EntityRef<ObjetoSegurado>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Documento", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Documento
		{
			get
			{
				return this._Documento;
			}
			set
			{
				if ((this._Documento != value))
				{
					this.OnDocumentoChanging(value);
					this.SendPropertyChanging();
					this._Documento = value;
					this.SendPropertyChanged("Documento");
					this.OnDocumentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataNascimento", DbType="DateTime NOT NULL")]
		public System.DateTime DataNascimento
		{
			get
			{
				return this._DataNascimento;
			}
			set
			{
				if ((this._DataNascimento != value))
				{
					this.OnDataNascimentoChanging(value);
					this.SendPropertyChanging();
					this._DataNascimento = value;
					this.SendPropertyChanged("DataNascimento");
					this.OnDataNascimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sexo", DbType="Int NOT NULL")]
		public int Sexo
		{
			get
			{
				return this._Sexo;
			}
			set
			{
				if ((this._Sexo != value))
				{
					this.OnSexoChanging(value);
					this.SendPropertyChanging();
					this._Sexo = value;
					this.SendPropertyChanged("Sexo");
					this.OnSexoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoCivil", DbType="Int NOT NULL")]
		public int EstadoCivil
		{
			get
			{
				return this._EstadoCivil;
			}
			set
			{
				if ((this._EstadoCivil != value))
				{
					this.OnEstadoCivilChanging(value);
					this.SendPropertyChanging();
					this._EstadoCivil = value;
					this.SendPropertyChanged("EstadoCivil");
					this.OnEstadoCivilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FoneResidencial", DbType="VarChar(100)")]
		public string FoneResidencial
		{
			get
			{
				return this._FoneResidencial;
			}
			set
			{
				if ((this._FoneResidencial != value))
				{
					this.OnFoneResidencialChanging(value);
					this.SendPropertyChanging();
					this._FoneResidencial = value;
					this.SendPropertyChanged("FoneResidencial");
					this.OnFoneResidencialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FoneCelular", DbType="VarChar(100)")]
		public string FoneCelular
		{
			get
			{
				return this._FoneCelular;
			}
			set
			{
				if ((this._FoneCelular != value))
				{
					this.OnFoneCelularChanging(value);
					this.SendPropertyChanging();
					this._FoneCelular = value;
					this.SendPropertyChanged("FoneCelular");
					this.OnFoneCelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rua", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Rua
		{
			get
			{
				return this._Rua;
			}
			set
			{
				if ((this._Rua != value))
				{
					this.OnRuaChanging(value);
					this.SendPropertyChanging();
					this._Rua = value;
					this.SendPropertyChanged("Rua");
					this.OnRuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numero", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Numero
		{
			get
			{
				return this._Numero;
			}
			set
			{
				if ((this._Numero != value))
				{
					this.OnNumeroChanging(value);
					this.SendPropertyChanging();
					this._Numero = value;
					this.SendPropertyChanged("Numero");
					this.OnNumeroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bairro", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Bairro
		{
			get
			{
				return this._Bairro;
			}
			set
			{
				if ((this._Bairro != value))
				{
					this.OnBairroChanging(value);
					this.SendPropertyChanging();
					this._Bairro = value;
					this.SendPropertyChanged("Bairro");
					this.OnBairroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEP", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string CEP
		{
			get
			{
				return this._CEP;
			}
			set
			{
				if ((this._CEP != value))
				{
					this.OnCEPChanging(value);
					this.SendPropertyChanging();
					this._CEP = value;
					this.SendPropertyChanged("CEP");
					this.OnCEPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cidade", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Cidade
		{
			get
			{
				return this._Cidade;
			}
			set
			{
				if ((this._Cidade != value))
				{
					this.OnCidadeChanging(value);
					this.SendPropertyChanging();
					this._Cidade = value;
					this.SendPropertyChanged("Cidade");
					this.OnCidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BonusAtual", DbType="VarChar(100)")]
		public string BonusAtual
		{
			get
			{
				return this._BonusAtual;
			}
			set
			{
				if ((this._BonusAtual != value))
				{
					this.OnBonusAtualChanging(value);
					this.SendPropertyChanging();
					this._BonusAtual = value;
					this.SendPropertyChanged("BonusAtual");
					this.OnBonusAtualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeguradoraAnterior", DbType="VarChar(100)")]
		public string SeguradoraAnterior
		{
			get
			{
				return this._SeguradoraAnterior;
			}
			set
			{
				if ((this._SeguradoraAnterior != value))
				{
					this.OnSeguradoraAnteriorChanging(value);
					this.SendPropertyChanging();
					this._SeguradoraAnterior = value;
					this.SendPropertyChanged("SeguradoraAnterior");
					this.OnSeguradoraAnteriorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroCNH", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string NumeroCNH
		{
			get
			{
				return this._NumeroCNH;
			}
			set
			{
				if ((this._NumeroCNH != value))
				{
					this.OnNumeroCNHChanging(value);
					this.SendPropertyChanging();
					this._NumeroCNH = value;
					this.SendPropertyChanged("NumeroCNH");
					this.OnNumeroCNHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimeiraHabilitacao", DbType="DateTime NOT NULL")]
		public System.DateTime PrimeiraHabilitacao
		{
			get
			{
				return this._PrimeiraHabilitacao;
			}
			set
			{
				if ((this._PrimeiraHabilitacao != value))
				{
					this.OnPrimeiraHabilitacaoChanging(value);
					this.SendPropertyChanging();
					this._PrimeiraHabilitacao = value;
					this.SendPropertyChanged("PrimeiraHabilitacao");
					this.OnPrimeiraHabilitacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Segurado_ObjetoSegurado", Storage="_ObjetoSegurados", ThisKey="Codigo", OtherKey="Segurado")]
		public EntitySet<ObjetoSegurado> ObjetoSegurados
		{
			get
			{
				return this._ObjetoSegurados;
			}
			set
			{
				this._ObjetoSegurados.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Segurado_ObjetoSegurado1", Storage="_ObjetoSegurado", ThisKey="Codigo", OtherKey="Codigo", IsUnique=true, IsForeignKey=false)]
		public ObjetoSegurado ObjetoSegurado
		{
			get
			{
				return this._ObjetoSegurado.Entity;
			}
			set
			{
				ObjetoSegurado previousValue = this._ObjetoSegurado.Entity;
				if (((previousValue != value) 
							|| (this._ObjetoSegurado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ObjetoSegurado.Entity = null;
						previousValue.Segurado2 = null;
					}
					this._ObjetoSegurado.Entity = value;
					if ((value != null))
					{
						value.Segurado2 = this;
					}
					this.SendPropertyChanged("ObjetoSegurado");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ObjetoSegurados(ObjetoSegurado entity)
		{
			this.SendPropertyChanging();
			entity.Segurado1 = this;
		}
		
		private void detach_ObjetoSegurados(ObjetoSegurado entity)
		{
			this.SendPropertyChanging();
			entity.Segurado1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ObjetoSegurado")]
	public partial class ObjetoSegurado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Codigo;
		
		private int _Segurado;
		
		private string _TipoAutomovel;
		
		private string _CodigoFipe;
		
		private string _Categoria;
		
		private System.Nullable<int> _Marca;
		
		private System.Nullable<int> _Modelo;
		
		private System.Nullable<int> _Potencia;
		
		private System.Nullable<System.DateTime> _AnoDeFabricacao;
		
		private System.Nullable<System.DateTime> _AnoModelo;
		
		private string _Chassi;
		
		private string _Placa;
		
		private System.Nullable<int> _QtdPortas;
		
		private System.Nullable<int> _NroPassageiros;
		
		private string _CepPernoite;
		
		private string _Renavam;
		
		private System.Nullable<decimal> _ValorFipe;
		
		private System.Nullable<decimal> _ValorCotado;
		
		private EntityRef<Marca> _Marca1;
		
		private EntityRef<Modelo> _Modelo1;
		
		private EntityRef<Segurado> _Segurado1;
		
		private EntityRef<Segurado> _Segurado2;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoChanging(int value);
    partial void OnCodigoChanged();
    partial void OnSeguradoChanging(int value);
    partial void OnSeguradoChanged();
    partial void OnTipoAutomovelChanging(string value);
    partial void OnTipoAutomovelChanged();
    partial void OnCodigoFipeChanging(string value);
    partial void OnCodigoFipeChanged();
    partial void OnCategoriaChanging(string value);
    partial void OnCategoriaChanged();
    partial void OnMarcaChanging(System.Nullable<int> value);
    partial void OnMarcaChanged();
    partial void OnModeloChanging(System.Nullable<int> value);
    partial void OnModeloChanged();
    partial void OnPotenciaChanging(System.Nullable<int> value);
    partial void OnPotenciaChanged();
    partial void OnAnoDeFabricacaoChanging(System.Nullable<System.DateTime> value);
    partial void OnAnoDeFabricacaoChanged();
    partial void OnAnoModeloChanging(System.Nullable<System.DateTime> value);
    partial void OnAnoModeloChanged();
    partial void OnChassiChanging(string value);
    partial void OnChassiChanged();
    partial void OnPlacaChanging(string value);
    partial void OnPlacaChanged();
    partial void OnQtdPortasChanging(System.Nullable<int> value);
    partial void OnQtdPortasChanged();
    partial void OnNroPassageirosChanging(System.Nullable<int> value);
    partial void OnNroPassageirosChanged();
    partial void OnCepPernoiteChanging(string value);
    partial void OnCepPernoiteChanged();
    partial void OnRenavamChanging(string value);
    partial void OnRenavamChanged();
    partial void OnValorFipeChanging(System.Nullable<decimal> value);
    partial void OnValorFipeChanged();
    partial void OnValorCotadoChanging(System.Nullable<decimal> value);
    partial void OnValorCotadoChanged();
    #endregion
		
		public ObjetoSegurado()
		{
			this._Marca1 = default(EntityRef<Marca>);
			this._Modelo1 = default(EntityRef<Modelo>);
			this._Segurado1 = default(EntityRef<Segurado>);
			this._Segurado2 = default(EntityRef<Segurado>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					if (this._Segurado2.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segurado", DbType="Int NOT NULL")]
		public int Segurado
		{
			get
			{
				return this._Segurado;
			}
			set
			{
				if ((this._Segurado != value))
				{
					if (this._Segurado1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSeguradoChanging(value);
					this.SendPropertyChanging();
					this._Segurado = value;
					this.SendPropertyChanged("Segurado");
					this.OnSeguradoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoAutomovel", DbType="VarChar(20)")]
		public string TipoAutomovel
		{
			get
			{
				return this._TipoAutomovel;
			}
			set
			{
				if ((this._TipoAutomovel != value))
				{
					this.OnTipoAutomovelChanging(value);
					this.SendPropertyChanging();
					this._TipoAutomovel = value;
					this.SendPropertyChanged("TipoAutomovel");
					this.OnTipoAutomovelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoFipe", DbType="VarChar(20)")]
		public string CodigoFipe
		{
			get
			{
				return this._CodigoFipe;
			}
			set
			{
				if ((this._CodigoFipe != value))
				{
					this.OnCodigoFipeChanging(value);
					this.SendPropertyChanging();
					this._CodigoFipe = value;
					this.SendPropertyChanged("CodigoFipe");
					this.OnCodigoFipeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categoria", DbType="VarChar(20)")]
		public string Categoria
		{
			get
			{
				return this._Categoria;
			}
			set
			{
				if ((this._Categoria != value))
				{
					this.OnCategoriaChanging(value);
					this.SendPropertyChanging();
					this._Categoria = value;
					this.SendPropertyChanged("Categoria");
					this.OnCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marca", DbType="Int")]
		public System.Nullable<int> Marca
		{
			get
			{
				return this._Marca;
			}
			set
			{
				if ((this._Marca != value))
				{
					if (this._Marca1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMarcaChanging(value);
					this.SendPropertyChanging();
					this._Marca = value;
					this.SendPropertyChanged("Marca");
					this.OnMarcaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modelo", DbType="Int")]
		public System.Nullable<int> Modelo
		{
			get
			{
				return this._Modelo;
			}
			set
			{
				if ((this._Modelo != value))
				{
					if (this._Modelo1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnModeloChanging(value);
					this.SendPropertyChanging();
					this._Modelo = value;
					this.SendPropertyChanged("Modelo");
					this.OnModeloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Potencia", DbType="Int")]
		public System.Nullable<int> Potencia
		{
			get
			{
				return this._Potencia;
			}
			set
			{
				if ((this._Potencia != value))
				{
					this.OnPotenciaChanging(value);
					this.SendPropertyChanging();
					this._Potencia = value;
					this.SendPropertyChanged("Potencia");
					this.OnPotenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnoDeFabricacao", DbType="DateTime")]
		public System.Nullable<System.DateTime> AnoDeFabricacao
		{
			get
			{
				return this._AnoDeFabricacao;
			}
			set
			{
				if ((this._AnoDeFabricacao != value))
				{
					this.OnAnoDeFabricacaoChanging(value);
					this.SendPropertyChanging();
					this._AnoDeFabricacao = value;
					this.SendPropertyChanged("AnoDeFabricacao");
					this.OnAnoDeFabricacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnoModelo", DbType="DateTime")]
		public System.Nullable<System.DateTime> AnoModelo
		{
			get
			{
				return this._AnoModelo;
			}
			set
			{
				if ((this._AnoModelo != value))
				{
					this.OnAnoModeloChanging(value);
					this.SendPropertyChanging();
					this._AnoModelo = value;
					this.SendPropertyChanged("AnoModelo");
					this.OnAnoModeloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chassi", DbType="VarChar(30)")]
		public string Chassi
		{
			get
			{
				return this._Chassi;
			}
			set
			{
				if ((this._Chassi != value))
				{
					this.OnChassiChanging(value);
					this.SendPropertyChanging();
					this._Chassi = value;
					this.SendPropertyChanged("Chassi");
					this.OnChassiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Placa", DbType="VarChar(10)")]
		public string Placa
		{
			get
			{
				return this._Placa;
			}
			set
			{
				if ((this._Placa != value))
				{
					this.OnPlacaChanging(value);
					this.SendPropertyChanging();
					this._Placa = value;
					this.SendPropertyChanged("Placa");
					this.OnPlacaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QtdPortas", DbType="Int")]
		public System.Nullable<int> QtdPortas
		{
			get
			{
				return this._QtdPortas;
			}
			set
			{
				if ((this._QtdPortas != value))
				{
					this.OnQtdPortasChanging(value);
					this.SendPropertyChanging();
					this._QtdPortas = value;
					this.SendPropertyChanged("QtdPortas");
					this.OnQtdPortasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NroPassageiros", DbType="Int")]
		public System.Nullable<int> NroPassageiros
		{
			get
			{
				return this._NroPassageiros;
			}
			set
			{
				if ((this._NroPassageiros != value))
				{
					this.OnNroPassageirosChanging(value);
					this.SendPropertyChanging();
					this._NroPassageiros = value;
					this.SendPropertyChanged("NroPassageiros");
					this.OnNroPassageirosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CepPernoite", DbType="VarChar(20)")]
		public string CepPernoite
		{
			get
			{
				return this._CepPernoite;
			}
			set
			{
				if ((this._CepPernoite != value))
				{
					this.OnCepPernoiteChanging(value);
					this.SendPropertyChanging();
					this._CepPernoite = value;
					this.SendPropertyChanged("CepPernoite");
					this.OnCepPernoiteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Renavam", DbType="VarChar(30)")]
		public string Renavam
		{
			get
			{
				return this._Renavam;
			}
			set
			{
				if ((this._Renavam != value))
				{
					this.OnRenavamChanging(value);
					this.SendPropertyChanging();
					this._Renavam = value;
					this.SendPropertyChanged("Renavam");
					this.OnRenavamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorFipe", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> ValorFipe
		{
			get
			{
				return this._ValorFipe;
			}
			set
			{
				if ((this._ValorFipe != value))
				{
					this.OnValorFipeChanging(value);
					this.SendPropertyChanging();
					this._ValorFipe = value;
					this.SendPropertyChanged("ValorFipe");
					this.OnValorFipeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorCotado", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> ValorCotado
		{
			get
			{
				return this._ValorCotado;
			}
			set
			{
				if ((this._ValorCotado != value))
				{
					this.OnValorCotadoChanging(value);
					this.SendPropertyChanging();
					this._ValorCotado = value;
					this.SendPropertyChanged("ValorCotado");
					this.OnValorCotadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Marca_ObjetoSegurado", Storage="_Marca1", ThisKey="Marca", OtherKey="ID", IsForeignKey=true)]
		public Marca Marca1
		{
			get
			{
				return this._Marca1.Entity;
			}
			set
			{
				Marca previousValue = this._Marca1.Entity;
				if (((previousValue != value) 
							|| (this._Marca1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Marca1.Entity = null;
						previousValue.ObjetoSegurados.Remove(this);
					}
					this._Marca1.Entity = value;
					if ((value != null))
					{
						value.ObjetoSegurados.Add(this);
						this._Marca = value.ID;
					}
					else
					{
						this._Marca = default(Nullable<int>);
					}
					this.SendPropertyChanged("Marca1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Modelo_ObjetoSegurado", Storage="_Modelo1", ThisKey="Modelo", OtherKey="ID", IsForeignKey=true)]
		public Modelo Modelo1
		{
			get
			{
				return this._Modelo1.Entity;
			}
			set
			{
				Modelo previousValue = this._Modelo1.Entity;
				if (((previousValue != value) 
							|| (this._Modelo1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Modelo1.Entity = null;
						previousValue.ObjetoSegurados.Remove(this);
					}
					this._Modelo1.Entity = value;
					if ((value != null))
					{
						value.ObjetoSegurados.Add(this);
						this._Modelo = value.ID;
					}
					else
					{
						this._Modelo = default(Nullable<int>);
					}
					this.SendPropertyChanged("Modelo1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Segurado_ObjetoSegurado", Storage="_Segurado1", ThisKey="Segurado", OtherKey="Codigo", IsForeignKey=true)]
		public Segurado Segurado1
		{
			get
			{
				return this._Segurado1.Entity;
			}
			set
			{
				Segurado previousValue = this._Segurado1.Entity;
				if (((previousValue != value) 
							|| (this._Segurado1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Segurado1.Entity = null;
						previousValue.ObjetoSegurados.Remove(this);
					}
					this._Segurado1.Entity = value;
					if ((value != null))
					{
						value.ObjetoSegurados.Add(this);
						this._Segurado = value.Codigo;
					}
					else
					{
						this._Segurado = default(int);
					}
					this.SendPropertyChanged("Segurado1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Segurado_ObjetoSegurado1", Storage="_Segurado2", ThisKey="Codigo", OtherKey="Codigo", IsForeignKey=true)]
		public Segurado Segurado2
		{
			get
			{
				return this._Segurado2.Entity;
			}
			set
			{
				Segurado previousValue = this._Segurado2.Entity;
				if (((previousValue != value) 
							|| (this._Segurado2.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Segurado2.Entity = null;
						previousValue.ObjetoSegurado = null;
					}
					this._Segurado2.Entity = value;
					if ((value != null))
					{
						value.ObjetoSegurado = this;
						this._Codigo = value.Codigo;
					}
					else
					{
						this._Codigo = default(int);
					}
					this.SendPropertyChanged("Segurado2");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
